name: cofoda
description: CodeForces Dashboard

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  fluro: ^1.6.3
  http: ^0.12.1
  url_launcher: ^5.5.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
