name: dashforces
description: codeforces dashboard

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  charts_flutter: ^0.9.0
  cloud_firestore: ^0.14.1+3
  cloud_functions: ^0.7.0-dev.2
  cupertino_icons: ^0.1.3
  firebase_core: ^0.5.0+1
  fluro: ^1.6.3
  http: ^0.12.1
  provider: ^4.3.2+2
  synchronized: ^2.2.0+2
  url_launcher: ^5.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
